services:
  - type: worker
    name: tgb-bot
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
